#服务器配置
server:
  port: 8001


#mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml       #mybatis的配置文件
  mapper-locations: classpath:mybatis/mapper/**/*.xml      #mapper的映射xml
  type-aliases-package: com.mysit.springclond.pojos        #mybatis的别名包

#spring的主配置
spring:
  application:
    name: microservicecloud-dept                           #这个名字非常重要，因为它对应的是你微服务暴露出去的服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clond01
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200
