#服务器配置
server:
  port: 8003


#mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml       #mybatis的配置文件
  mapper-locations: classpath:mybatis/mapper/**/*.xml      #mapper的映射xml
  type-aliases-package: com.mysit.springclond.pojos        #mybatis的别名包

#spring的主配置
spring:
  application:
    name: microservicecloud-dept                           #这个名字非常重要，因为它对应的是你微服务暴露出去的服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clond03
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200
#eureka客户端配置
eureka:
  client:  #客户端注册进入服务器端地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microserviceclond-dept8003           #自定义实例id
    prefer-ip-address: true                           #设置访问地址可以显示ip地址

info:
  app.name: mysit-microserviceclond
  company.name: www.mysit.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


