server:
  port: 9527

spring:
  application:
    name: microserviceclond-zuul-gateway            #注册进入Eureka里面唯一的微服务名称
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

info:
  app.name: mysit-microserviceclond
  company.name: www.mysit.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul:
  routes:
    dept:                       #部门服务路由映射配置
      path: /dept/**
      service-id: MICROSERVICECLOUD-DEPT
  ignored-services: "*"         #忽略所有的服务名映射
  prefix: /springclond          #添加统一的url请求前缀名称

